#version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: next5-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: next5_db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - next5-network

  redis:
    image: redis:7
    container_name: next5-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - next5-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: next5-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    command: >
      bash -c '
        bin/elasticsearch-plugin install analysis-nori;
        /usr/local/bin/docker-entrypoint.sh elasticsearch
      '
    ports:
      - "9200:9200"
    profiles: ["elk"]
    networks:
      - next5-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: next5-kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    profiles: ["elk"]
    depends_on:
      - elasticsearch
    networks:
      - next5-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.3
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/lib/mysql-connector-j-9.2.0.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-j-9.2.0.jar:ro
    ports:
      - "5001:5001"
      - "5044:5044"
    profiles: ["elk"]
    depends_on:
      - elasticsearch
    networks:
      - next5-network


networks:
  next5-network:
    driver: bridge
volumes:
    db-data: