spring:
  config:
    activate:
      on-profile: prod

  server:
    address: 0.0.0.0
    port: 8080

  datasource:
    url: ${SPRING__DATASOURCE__URL}
    username: ${SPRING__DATASOURCE__USERNAME}
    password: ${SPRING__DATASOURCE__PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING__REDIS__HOST}
      port: ${SPRING__REDIS__PORT}
      password: ${SPRING__REDIS__PASSWORD}

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}

logging:
  level:
    root: info
