spring:
  profiles: ci

  datasource:
    url: jdbc:h2:mem:ci_db;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트 끝나면 DB 초기화
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  cache:
    type: none  # CI 환경에서는 Redis 없이 실행

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}
  access-exp: 3600000
  refresh-exp: 604800000
