services:
  prometheus:
    image: prom/prometheus
    container_name: next5-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - next5-monitoring

  grafana:
    image: grafana/grafana
    container_name: next5-grafana
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin1234
    networks:
      - next5-monitoring

  influxdb:
    image: influxdb:1.8
    container_name: next5-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - next5-monitoring

networks:
  next5-monitoring:
    driver: bridge
