name: Deploy Next5 to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test


      - name: Upload JAR to EC2
        env:
          SSH_KEY_B64: ${{ secrets.EC2_SSH_KEY_B64 }}
        run: |
          printf "%b" "$SSH_KEY_B64" | base64 -d > key.pem
          chmod 600 key.pem

          echo "----- START key.pem -----"
          sed -n '1,20p' key.pem
          echo "----- END key.pem -----"

          scp -o StrictHostKeyChecking=no -i key.pem \
            build/libs/*.jar \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/next5_dev/app.jar


      - name: Restart next5 service
        env:
          SSH_KEY_B64: ${{ secrets.EC2_SSH_KEY_B64 }}
        run: |
          printf "%b" "$SSH_KEY_B64" | base64 -d > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo systemctl restart next5"
